/* eslint-disable @next/next/no-img-element */
import React from 'react'
import PlanYourBookComp from '@/pages/publish/plan-your-book/PlanYourBookComp';


export const metadata = {
    title: "Plan Your Book: Print Book and Ebook | IngramSpark",
    description: "Generated by create next app",
    icons: {
        icon: '/IngramSparkLogo.webp'
    }
};

const PlanYourBook = () => {

    return (
      <PlanYourBookComp />
    )
}

export default PlanYourBook